### PR TITLE
Chrome video bugfix, automatically use hostname, documentation for travis

### PR DESCRIPTION
**Pull request by bryanhe**

### CODE REVIEW

**Comment by alexjball** [comment]
When did you see the video glitch?

Are you using GITHUB_TOKEN so you can deploy on your own fork? Travis only deploys the client, and the client should be able to connect to any room server, so you only need to deploy your own client if you're making changes to it and want those to be public. But agree that it's better to follow the doc recs and use a variable

**Comment by bryanhe** [comment]
Chrome on left, Firefox on right:


Cursor buttons on chrome:


Travis bugged out when I left your key in. I was just kind of wandering around in the dark, so I had to slowly get rid of errors to figure out if I was on the right track.

**Comment by alexjball** [comment]
Interesting, my controls look different on Chrome 78. Are you using chrome or chromium, OS?
Screenshot from 2019-11-12 23-44-32

**Comment by bryanhe** [comment]
> google-chrome-stable --version
Google Chrome 63.0.3239.84 

OS is Arch.

**Comment by alexjball** [comment]
Sweet, thanks, I'll chalk it up to chrome version differences.

I made the deployment conditional on GITHUB_TOKEN being set, so travis should work on forks without having to set up a token (and so without GH deployment). Thanks for the help making contributing easier!

**Pull request merged**
